### ISSUE TITLE
最新版easyswoole疑问点

### ISSUE THREAD

**Issue by candivan** [easyswoole-panel/easyswoole_panel#15]
1，权限没办法删除和修改。
2,"easyswoole/code-generation": "^2.0",这个估计和哪里冲突了，我composer里面删除了，才可以composer install成功，不然会报以下错误： 
`
Problem 1
    - easyswoole/code-generation[2.0.1, ..., 2.0.2] require easyswoole/http-annotation ^1.4 -> satisfiable by easyswoole/http-annotation[1.4.0, ..., 1.5.0].
    - You can only install one version of a package, so only one of these can be installed: easyswoole/http-annotation[1.4.0, ..., 1.5.0, 2.0.0].
    - easyswoole/easyswoole 3.x-dev requires easyswoole/http-annotation ^2.0 -> satisfiable by easyswoole/http-annotation[2.0.0].
    - Root composer.json requires easyswoole/easyswoole 3.x-dev -> satisfiable by easyswoole/easyswoole[3.x-dev].
    - Root composer.json requires easyswoole/code-generation ^2.0 -> satisfiable by easyswoole/code-generation[2.0.1, 2.0.2].
`

**Comment by gaobinzhan** [comment]
主框架版本改成`3.4.x`
